# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lago < Formula
  desc "Official CLI for the Lago billing platform"
  homepage "https://getlago.com"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/getlago/lago-cli/releases/download/v1.0.0/lago_1.0.0_darwin_amd64.tar.gz"
      sha256 "8ed5447b36b5d0d43dc1dd70e00fdb558aa2b0de5df98b5e322dc39df07b315d"

      define_method(:install) do
        bin.install "lago"
        man1.install "man/lago.1"
        bash_completion.install "completions/lago.bash" => "lago"
        zsh_completion.install "completions/_lago"
        fish_completion.install "completions/lago.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/getlago/lago-cli/releases/download/v1.0.0/lago_1.0.0_darwin_arm64.tar.gz"
      sha256 "441657626af81b6dd634de6821e5b817da84ca060bc52a822c72cd39fdca3363"

      define_method(:install) do
        bin.install "lago"
        man1.install "man/lago.1"
        bash_completion.install "completions/lago.bash" => "lago"
        zsh_completion.install "completions/_lago"
        fish_completion.install "completions/lago.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/getlago/lago-cli/releases/download/v1.0.0/lago_1.0.0_linux_amd64.tar.gz"
      sha256 "d45a5761ee87785c6b489c28af37977c618b89660a864faae469051820f6cb0e"
      define_method(:install) do
        bin.install "lago"
        man1.install "man/lago.1"
        bash_completion.install "completions/lago.bash" => "lago"
        zsh_completion.install "completions/_lago"
        fish_completion.install "completions/lago.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/getlago/lago-cli/releases/download/v1.0.0/lago_1.0.0_linux_arm64.tar.gz"
      sha256 "442b5c8b4d64223554a4da87d785d47ffa9df0536a94be62d9b66ac3b980b4ff"
      define_method(:install) do
        bin.install "lago"
        man1.install "man/lago.1"
        bash_completion.install "completions/lago.bash" => "lago"
        zsh_completion.install "completions/_lago"
        fish_completion.install "completions/lago.fish"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/lago version --output json")
  end
end
