# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lago < Formula
  desc "Official CLI for the Lago billing platform"
  homepage "https://getlago.com"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/getlago/lago-cli/releases/download/v1.0.1/lago_1.0.1_darwin_amd64.tar.gz"
      sha256 "b5ec452310373f737d287500bc81f3c9995545c70ca475faa0be81623b824101"

      define_method(:install) do
        bin.install "lago"
        man1.install "man/lago.1"
        bash_completion.install "completions/lago.bash" => "lago"
        zsh_completion.install "completions/_lago"
        fish_completion.install "completions/lago.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/getlago/lago-cli/releases/download/v1.0.1/lago_1.0.1_darwin_arm64.tar.gz"
      sha256 "8635dada724c3d54f86690a4a185ad5526b9483575c0bfda1408f9be12a635af"

      define_method(:install) do
        bin.install "lago"
        man1.install "man/lago.1"
        bash_completion.install "completions/lago.bash" => "lago"
        zsh_completion.install "completions/_lago"
        fish_completion.install "completions/lago.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/getlago/lago-cli/releases/download/v1.0.1/lago_1.0.1_linux_amd64.tar.gz"
      sha256 "c22496eadf1b9faf0c204d8740925a59a0dc2f7515874478def89271f162a467"
      define_method(:install) do
        bin.install "lago"
        man1.install "man/lago.1"
        bash_completion.install "completions/lago.bash" => "lago"
        zsh_completion.install "completions/_lago"
        fish_completion.install "completions/lago.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/getlago/lago-cli/releases/download/v1.0.1/lago_1.0.1_linux_arm64.tar.gz"
      sha256 "933bef9d51a2572b0c3b7f46489eb25123319f751eb3fc8ebc707f0ec51d5da0"
      define_method(:install) do
        bin.install "lago"
        man1.install "man/lago.1"
        bash_completion.install "completions/lago.bash" => "lago"
        zsh_completion.install "completions/_lago"
        fish_completion.install "completions/lago.fish"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/lago version --output json")
  end
end
