# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lago < Formula
  desc "Official CLI for the Lago billing platform"
  homepage "https://getlago.com"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/getlago/lago-cli/releases/download/v1.0.2/lago_1.0.2_darwin_amd64.tar.gz"
      sha256 "4c0ca7ed52d32b93c68de64593bdbed90ddfb228b7d5e0549f9cfadf3ab25f27"

      define_method(:install) do
        bin.install "lago"
        man1.install "man/lago.1"
        bash_completion.install "completions/lago.bash" => "lago"
        zsh_completion.install "completions/_lago"
        fish_completion.install "completions/lago.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/getlago/lago-cli/releases/download/v1.0.2/lago_1.0.2_darwin_arm64.tar.gz"
      sha256 "7e2f1cacf1481fc1cad1516f5b55cc5b9fd4b292907ef779addab8b8ebeaea6b"

      define_method(:install) do
        bin.install "lago"
        man1.install "man/lago.1"
        bash_completion.install "completions/lago.bash" => "lago"
        zsh_completion.install "completions/_lago"
        fish_completion.install "completions/lago.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/getlago/lago-cli/releases/download/v1.0.2/lago_1.0.2_linux_amd64.tar.gz"
      sha256 "fbf8578f55a284820d4eed6c042ac18c63654d32b844fb9847880f9cd7209935"
      define_method(:install) do
        bin.install "lago"
        man1.install "man/lago.1"
        bash_completion.install "completions/lago.bash" => "lago"
        zsh_completion.install "completions/_lago"
        fish_completion.install "completions/lago.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/getlago/lago-cli/releases/download/v1.0.2/lago_1.0.2_linux_arm64.tar.gz"
      sha256 "ec317047636d30ed3f163b38af4403dc72459ce6de982c58946f30d00eb742cf"
      define_method(:install) do
        bin.install "lago"
        man1.install "man/lago.1"
        bash_completion.install "completions/lago.bash" => "lago"
        zsh_completion.install "completions/_lago"
        fish_completion.install "completions/lago.fish"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/lago version --output json")
  end
end
